CREATE USER example_user WITH LOGIN ENCRYPTED PASSWORD 'example_pass';
CREATE DATABASE example_db WITH OWNER example_user;
\c example_db;
GRANT ALL PRIVILEGES ON DATABASE example_db TO example_user;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO example_user;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO example_user;