\c example_db;
CREATE TABLE public.user (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    token text,
    tokenexpire timestamp with time zone
);